### ISSUE TITLE
I made a fork for myself

### ISSUE THREAD

**Issue by Groctel** [PontusHanssen/pddl.vim#2]
Hey! I forked your plugin and re-wrote it to be more coloured and regex-based: https://github.com/Groctel/pddl.vim/. I'm not making a formal PR because syntax highlights are very dependent on the end user tastes, but I wanted to give you a heads up in case you want to adopt some of my changes. ❤️❤️❤️

**Comment by PontusHanssen** [comment]
I'm happy this little project could be of use!
I think you made the right call forking the project instead of sending me PRs seeing how quick I am to reply to issues :sweat_smile: 

I'm closing this issue, happy holidays :santa:
